### ISSUE TITLE
Implementing flow-definition handler

### ISSUE THREAD

**Issue by dothebart** [ktdreyer/jenkins-job-wrecker#43]
Hi, 
I'm trying to implement the handling of the new pipeline jobs. 
I've hooked `'flow-definition': 'flow'` into `registry.py`

if I get that correctly, from that point in `handlers.py` I'd need to self call the same way cli.py does, I've tried: 
```
def definition(top, parent):

    reg = Registry()
    handlers = Handlers(reg)
    for child in top:
        handlers.gen_yml(top, child)

    parent.append(['definitionxxx',top.text])
```    
but it won't know the attributes of scm:
```
last called configversion
last called definition
Traceback (most recent call last):
  File "/usr/local/bin/jjwrecker", line 11, in <module>
    load_entry_point('jenkins-job-wrecker==1.3.0', 'console_scripts', 'jjwrecker')()
  File "/usr/local/lib/python2.7/dist-packages/jenkins_job_wrecker/cli.py", line 157, in main
    yaml = root_to_yaml(root, args.name)
  File "/usr/local/lib/python2.7/dist-packages/jenkins_job_wrecker/cli.py", line 73, in root_to_yaml
    handlers.gen_yml(job, root)
  File "/usr/local/lib/python2.7/dist-packages/jenkins_job_wrecker/modules/handlers.py", line 16, in gen_yml
    self.registry.dispatch(self.component, handler_name, child, settings)
  File "/usr/local/lib/python2.7/dist-packages/jenkins_job_wrecker/registry.py", line 61, in dispatch
    self.registry[component][name](xml, parent)
  File "/usr/local/lib/python2.7/dist-packages/jenkins_job_wrecker/modules/handlers.py", line 181, in definition
    handlers.gen_yml(top, child)
  File "/usr/local/lib/python2.7/dist-packages/jenkins_job_wrecker/modules/handlers.py", line 16, in gen_yml
    self.registry.dispatch(self.component, handler_name, child, settings)
  File "/usr/local/lib/python2.7/dist-packages/jenkins_job_wrecker/registry.py", line 59, in dispatch
    my_obj = self.registry[component][name]
KeyError: 'configversion'
```
any hints how I could do that? 

Heres a sample `config.xml` which I'm trying to parse:

```
<?xml version='1.0' encoding='UTF-8'?>
<flow-definition plugin="workflow-job@2.9">
  <actions/>
  <description></description>
  <keepDependencies>false</keepDependencies>
  <properties>
    <com.coravy.hudson.plugins.github.GithubProjectProperty plugin="github@1.24.0">
      <projectUrl>https://github.com/arangodb/arangodb/</projectUrl>
      <displayName></displayName>
    </com.coravy.hudson.plugins.github.GithubProjectProperty>
    <hudson.model.ParametersDefinitionProperty>
      <parameterDefinitions>
        <hudson.model.StringParameterDefinition>
          <name>GITTAG</name>
          <description></description>
          <defaultValue>3.1.4</defaultValue>
        </hudson.model.StringParameterDefinition>
        <hudson.model.StringParameterDefinition>
          <name>preferBuilder</name>
          <description>leave empty to build all; specify one of the docker containers elsewhise:
centosix, centoseven, fedoratwentythree, opensusethirteen, debianjessie, ubuntutwelveofour, ubuntufourteenofour, ubuntusixteenofour</description>
          <defaultValue></defaultValue>
        </hudson.model.StringParameterDefinition>
        <hudson.model.BooleanParameterDefinition>
          <name>CLEAN_BUILDENV</name>
          <description>whether we should flush eventually existing previous build attempts; If not, we may be faster, but struggle over previous errors.</description>
          <defaultValue>false</defaultValue>
        </hudson.model.BooleanParameterDefinition>
        <hudson.model.BooleanParameterDefinition>
          <name>NEW_MAJOR_RELEASE</name>
          <description>wher this is a .0 release - moves latest tag in the official docker library</description>
          <defaultValue>false</defaultValue>
        </hudson.model.BooleanParameterDefinition>
        <hudson.model.BooleanParameterDefinition>
          <name>SKIP_BUILD</name>
          <description>check if you don&apos;t want to recompile</description>
          <defaultValue>false</defaultValue>
        </hudson.model.BooleanParameterDefinition>
        <hudson.model.BooleanParameterDefinition>
          <name>SKIP_REPOBUILD</name>
          <description>Do you want to skip Copy &amp; repobuilding of packages?</description>
          <defaultValue>false</defaultValue>
        </hudson.model.BooleanParameterDefinition>
        <hudson.model.BooleanParameterDefinition>
          <name>SKIP_DOCKER_PUBLISH</name>
          <description>whether we want to ommit all those docker pushes</description>
          <defaultValue>false</defaultValue>
        </hudson.model.BooleanParameterDefinition>
        <hudson.model.BooleanParameterDefinition>
          <name>IS_RELEASE</name>
          <description>Uncheck when this in an alpha or release candidate; certain jobs won&apos;t run then: 
 - RELEASE__UpdateGithubMaster
 - RELEASE__BuildAMI
 - RELEASE__UpdateDockerResources
 - RELEASE__BuildHomebrew
</description>
          <defaultValue>true</defaultValue>
        </hudson.model.BooleanParameterDefinition>
      </parameterDefinitions>
    </hudson.model.ParametersDefinitionProperty>
    <org.jenkinsci.plugins.workflow.job.properties.PipelineTriggersJobProperty>
      <triggers/>
    </org.jenkinsci.plugins.workflow.job.properties.PipelineTriggersJobProperty>
  </properties>
  <definition class="org.jenkinsci.plugins.workflow.cps.CpsScmFlowDefinition" plugin="workflow-cps@2.23">
    <scm class="hudson.plugins.git.GitSCM" plugin="git@3.0.1">
      <configVersion>2</configVersion>
      <userRemoteConfigs>
        <hudson.plugins.git.UserRemoteConfig>
          <url>https://github.com/arangodb-helper/JenkinsScripts/</url>
        </hudson.plugins.git.UserRemoteConfig>
      </userRemoteConfigs>
      <branches>
        <hudson.plugins.git.BranchSpec>
          <name>*/master</name>
        </hudson.plugins.git.BranchSpec>
      </branches>
      <doGenerateSubmoduleConfigurations>false</doGenerateSubmoduleConfigurations>
      <submoduleCfg class="list"/>
      <extensions/>
    </scm>
    <scriptPath>release/Flow.groovy</scriptPath>
  </definition>
  <triggers/>
</flow-definition>
```

**Comment by ktdreyer** [comment]
@dothebart , is this working for you now?

**Comment by dothebart** [comment]
Sorry, I gave up on that approach E_NOTIME - I'm simply copying over ugly xml files now :-(
