### ISSUE TITLE
UnboundLocalError: local variable 'subelement' referenced before assignment

### ISSUE THREAD

**Issue by mbacchi** [ktdreyer/jenkins-job-wrecker#87]
While running the jjwrecker command I got the error:

```
(venv2) [user@host dir]$ jjwrecker -f jenkins-job.xml -n jenkins-job-wrecked.yml
last called buildwrappers
Traceback (most recent call last):
  File "/home/user/dir/venv2/bin/jjwrecker", line 11, in <module>
    sys.exit(main())
  File "/home/user/dir/venv2/lib/python2.7/site-packages/jenkins_job_wrecker/cli.py", line 196, in main
    yaml = root_to_yaml(root, args.name, args.ignore_actions_tag)
  File "/home/user/dir/venv2/lib/python2.7/site-packages/jenkins_job_wrecker/cli.py", line 97, in root_to_yaml
    handlers.gen_yml(job, root)
  File "/home/user/dir/venv2/lib/python2.7/site-packages/jenkins_job_wrecker/modules/handlers.py", line 16, in gen_yml
    self.registry.dispatch(self.component, handler_name, child, settings)
  File "/home/user/dir/venv2/lib/python2.7/site-packages/jenkins_job_wrecker/registry.py", line 64, in dispatch
    handler.gen_yml(parent, xml)
  File "/home/user/dir/venv2/lib/python2.7/site-packages/jenkins_job_wrecker/modules/buildwrappers.py", line 12, in gen_yml
    self.registry.dispatch(self.component, object_name, child, wrappers)
  File "/home/user/dir/venv2/lib/python2.7/site-packages/jenkins_job_wrecker/registry.py", line 60, in dispatch
    self.registry[component][name](xml, parent)
  File "/home/user/dir/venv2/lib/python2.7/site-packages/jenkins_job_wrecker/modules/buildwrappers.py", line 165, in prebuildcleanup
    "XML %s" % subelement.tag)
UnboundLocalError: local variable 'subelement' referenced before assignment
```

Fixed it with a simple s/subelement/element/ on line 165 for which I'll open a PR.

**Comment by ktdreyer** [comment]
I've [released 1.7.1](https://pypi.org/project/jenkins-job-wrecker/) with your change. Thanks!
